travis:
  secure:
    BINSTAR_TOKEN: NFbSDnuy2t9t1gazLIn6tF7FHAKDlH0FiSBUr7KFV2ypJ/ya/sOeKt3axo6K9EenMqBwGoD68ey5aZVa6MYBK70ViPqAc0TCNk7Qfky7BLf3qQ+FgDVOYfiUAf5wmkRNx6zqmMmeRaOvIgIafXcTMgg6zKggFNZVrjMoVFTeTEyZvnkXzwKXFskeI9JebrcmN84P4foT52rR4GL8hWu0WzMKeJBUcMUarbuw3ogFDaOyKI+bTEHD1Ca0XmOLZQ3PJkdfgrSAOll4hfR5TsrVGdIfA/7sgvem2hfMMy/Iusgp/d0jXtMT5Vlc0Sl0Wvfbpc6tlDX72mD3zDUwNxgwsYGsJ3VK15ays37jjCKu3bF7i1kUe6/msSdNCfl5toU8Dv/1EADeW65YffMyCEw52tCnFO3GAZUI/64+m8fIkZckxggG2hgTYMm3id53drB6aDa/YvtQOpu4Wzu6+KSguQ0Z0JLMD6JD3RZxcyHnT9IERJIpNh+HtjUaoPu3c4rWUYtuySjhKMigCw69a/prtHzrKJc6vBjl0MopNMdFIo/7UG0G6QKd465VXTflwxO88APuemGBqXReaI71/s4wURvG5prIb+lFFtcuwZN5JJlfUzLmvRbcUftVWYvVlqQza4ItjrZzpPpE0fYEGf5iJR7iFf/s0WSrk5Xy7O98xGM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
